### PR TITLE
Ldc fix

### PR DESCRIPTION
**Pull request by hover2pi**
Added error page redirects and input type checks to secure the LDC form. Everything works too.

### CODE REVIEW

**Comment by julesfowler** [comment]
@hover2pi Hey Joe, I'm making all of our branches one big happy family now -- but I cannot get the `svo_filters` import to work in anything other than the directory of install, and even then, it doesn't recognize the `svo_filters()['Band']` -- despite pulling and downloading the newest `svo_filters` repo. Do you know how we can fix this?

**Comment by julesfowler** [comment]
@hover2pi I figured out how to fix the import statement -- you need `import svo_filters.svo as svo` -- but I still can't get the import working right. Is there are environment variable to set or something?

**Comment by hover2pi** [comment]
@julesfowler I actually removed the dependency for svo_filters. There is a module called svo in the package now so you only need `from .. import svo`.

**Comment by mattjhill** [comment]
Also would help to have reasonable defaults for the boxes in "Choose Filter"

**Comment by hover2pi** [comment]
Thanks @mattjhill. Making the changes now.

**Comment by hover2pi** [comment]
This looks ready to go. Any reservations @mattjhill or @julesfowler?

**Pull request merged**
